server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        
        - id: EXPENSE-SERVICE
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/api/expense/**
        
        - id: PUSH-NOTIFICATION-SERVICE
          uri: lb://PUSH-NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notification/**
          filters:
            - RewritePath=/api/notification/ws, /ws
            
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedMethods: "*"
            allowedHeaders: "*"

  websocket:
    enabled: true 
