#
#
#server:
#  port: 8080
#  
#spring:
#  application:
#    name: API_GATEWAY 
#    
#
#  cloud:
#    gateway:
#      routes:
#      - id: USER-SERVICE
#        uri:
#          lb://USER-SERVICE
#        predicates:
#        - Path=/api/user/**
#        
#      
#        
#      - id: EXPENSE-SERVICE
#        uri:
#          lb://EXPENSE-SERVICE
#        predicates:
#        - Path=/api/expense/**
#         
#      
#         
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#              allowedOrigins: "*"
#              allowedMethods: "*"
#              allowedHeaders: "*"  
#  


server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        
        - id: EXPENSE-SERVICE
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/api/expense/**
        
        - id: PUSH-NOTIFICATION-SERVICE
          uri: lb://PUSH-NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notification/**
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

  websocket:
    enabled: true 
